---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170816122823"
editor:
  name: "AddJenkinsfileWebhookEditor"
  group: "atomist"
  artifact: "enrollment-rugs"
  version: "0.3.37"
  origin:
    repo: "git@github.com:atomisthq/enrollment-rugs"
    branch: "master"
    sha: "cc6a3b9"
  parameters:
    - "atomistWebhookUrl": "https://webhook.atomist.com/atomist/jenkins"

